# File: .github/workflows/repo-sync.yml
name: Sync OSS version from upstream

on:
  schedule:
  - cron:  "0 */12 * * *"

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: repo-sync
      uses: repo-sync/github-sync@v2
      with:
        source_repo: "hivemq/hivemq-mqtt-web-client"
        source_branch: "master"
        destination_branch: "upstream"
        github_token: ${{ secrets.GITHUB_TOKEN }}